---
  - name: install/uninstall s/w application
    hosts: all
    tasks:
      - name: install uninstall
        apt:
          name: "{{item.a}}"
          state: "{{item.b}}"
          update_cache: "{{item.c}}"
        with_items:
          - {a: git,b: present,c: yes}
          - {a: tree,b: absent,c: no}
          - {a: maven, b: present,c: yes}
...


