---
- name: create multiple users and copy files into user home dir
  hosts: all
  tasks:
    - name: create multiple users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: raju,b: ind,c: /home/raju}
        - {a: rani,b: rani,c: /tmp/rani}
    - name: copy files into user home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/raju}
        - {a: /etc/group,b: /tmp/rani}
