---
- name: create users and create files/dirs in user home dir
  hosts: all
  tasks:
    - name: user creation
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: creat files/dirs in users home dir
      file:
        name: "{{d}}"
        state: "{{e}}"
...
