---
- name: install git in ubuntu and red server
  hosts: all
  tasks:
    - name: install git in ubuntu using apt module
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install git in red using yum module
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"

