---
- name: configure tomcat
  hosts: all
  tasks:
    - name: install tomcat9
      apt:
        name: tomcat9
        state: present
        update_cache: yes
    - name: install tomcat9-admin
      apt:
        name: tomcat9-admin
        state: present
    - name: copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
    - name: change port of tomcat9
      replace:
        regexp: 8080
        replace: 1010
        path: /etc/tomcat9/server.xml
    - name: restart tomcat9
      service: 
        name: tomcat9
        state: restarted
    - name: pause for 1 min
      pause:
        minutes: 1
    - name: check tomcat at server1
      uri:
        url: http://172.32.25.57:1010
        status_code: 200
    - name: check tomcat at server
      uri:
        url: http://172.31.25.230:1010
        status_code: 200
