---
- name: creat user host scope
  hosts: 172.31.15.140
  tasks:
    - name: creat user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
        shell: "{{e}}"
        comment: "{{f}}"
...
